// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RequestHistory { id: number, url: string, status_code: number, response_time_ms: number, response_body: string, created_at: string, request_id: number, }