// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Request {
  id: bigint;
  url: string;
  name: string;
  method: string;
  headers: string;
  body: string | null;
  created_at: string;
}
