// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RequestHistory {
  id: bigint;
  url: string;
  request_headers: string;
  request_body: string | null;
  request_method: string;
  response_status_code: bigint;
  response_time_ms: bigint;
  response_body: string;
  created_at: string;
  request_id: bigint;
}
